spring:
  datasource:
    url: "jdbc:postgresql://${spring.database.host}:${spring.database.port}/${spring.database.name}"
    username: "${spring.database.username}"
    password: "${spring.database.password}"
    driver-class-name: "org.postgresql.Driver"
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: "${github-client-id}"
            clientSecret: "${github-client-secret}"
  database:
    host: "localhost"
    port: 5432
    name: "myfinancedb"
    username: "root"
    password: "admin"

  flyway:
    enabled: true

aws:
  cloudfront:
    distribution-id: 'E3BLJUPW5Z17RL'
  s3:
    bucket-name: myfinance-data